In [1]:
# Dependencies
import pandas as pd

In [2]:
# Read in file
file = 'Resources/clean_separated_list_count.csv'
df = pd.read_csv(file, encoding="ISO-8859-1")
df.head()

,date,team,player,position,status,crimeraw,desc,outcome,crime1,crime2,crime3,crime_list,crime_count
0,1/17/2020,NE,Joejuan Williams,CB,Arrested,drugs,"Pulled over for speeding in Nashville, accused...",Resolution undetermined.,drugs,NaN,NaN,['drugs'],1
1,1/16/2020,CLE,Odell Beckham,WR,Warrant,battery,Accused of slapping the buttocks of a police o...,Warrant rescinded.,battery,NaN,NaN,['battery'],1
2,1/11/2020,NE,Julian Edelman,WR,Arrested,vandalism,Accused of jumping on the hood of a Mercedes i...,Resolution undetermined.,vandalism,NaN,NaN,['vandalism'],1
3,12/29/2019,MIA,Xavien Howard,CB,Arrested,domestic violence,"Police in Davie, Fla., say he pushed his fianc...",Resolution undetermined.,domestic violence,NaN,NaN,['domestic violence'],1
4,12/20/2019,PIT,Kameron Kelly,S,Arrested,disorderly conduct,Accused of making threats and resisting arrest...,Resolution undetermined. Team released him sam...,disorderly conduct,NaN,NaN,['disorderly conduct'],1

In [3]:
offense = ['WR', 'RB', 'OT', 'TE', 'QB', 'OC', 'OG', 'FB', 'K', 'OL', 'C', 'P']
defense = ['CB', 'S', 'DT', 'LB', 'DE', 'DB', 'DT']

In [4]:
offense_crime_df = df.loc[df.position.isin(offense), ["player", "position", "crimeraw", "crime_count"]]
offense_crime_df

               player position            crimeraw  crime_count
1       Odell Beckham       WR             battery            1
2      Julian Edelman       WR           vandalism            1
6         Mark Walton       RB   domestic violence            1
9        Davion Davis       WR                 dui            1
15   Desmond Harrison       OT   domestic violence            1
..                ...      ...                 ...          ...
945       Andre Rison       WR               theft            1
946     Wayne Chrebet       WR  disorderly conduct            1
947       Keith Elias       RB  disorderly conduct            1
949         Fred Lane       RB          drugs, gun            2
951         Rod Smith       WR   domestic violence            1

[442 rows x 4 columns]

In [5]:
defense_crime_df = df.loc[df.position.isin(defense), ["player", "position", "crimeraw", "crime_count"]]
defense_crime_df

               player position            crimeraw  crime_count
0    Joejuan Williams       CB               drugs            1
3       Xavien Howard       CB   domestic violence            1
4       Kameron Kelly        S  disorderly conduct            1
5       Antwaun Woods       DT               drugs            1
7         Daniel Ross       DT          drugs, gun            2
..                ...      ...                 ...          ...
931   Charles Woodson       CB                 dui            1
932   Chris McAlister       CB               drugs            1
937       Steve Foley       LB                 gun            1
948       Steve Foley       LB   domestic violence            1
950         Ray Lewis       LB              murder            1

[509 rows x 4 columns]

In [6]:
# Exports the dataframes to CSV files
offense_crime_df.to_csv('Resources/offense_crime.csv', index=False)
defense_crime_df.to_csv('Resources/defense_crime.csv', index=False)